// ═══════════════════════════════════════════
//  SUNNY STEPS — Question Data
//  6 worlds × 8 questions each = 48 questions
// ═══════════════════════════════════════════

const WORLDS = {

  numbers: {
    title: '🔢 Numbers & Colors',
    progressColor: '#e0a800',
    cardClass: 'wc-numbers',
    questions: [
      {
        icon: '🍎🍎🍎',
        text: 'How many apples are there?',
        sub: 'Count them together!',
        choices: [
          { emoji: '1️⃣', label: 'One' },
          { emoji: '2️⃣', label: 'Two' },
          { emoji: '3️⃣', label: 'Three' },
          { emoji: '4️⃣', label: 'Four' },
        ],
        answer: '3️⃣',
        praise: 'Yes! 1, 2, 3 — three apples! 🍎',
        tip: 'Point to each apple together and count out loud: one… two… three!',
      },
      {
        icon: '🔵',
        text: 'What color is this circle?',
        sub: 'Look at the big circle!',
        choices: [
          { emoji: '🟡', label: 'Yellow' },
          { emoji: '🔴', label: 'Red' },
          { emoji: '🔵', label: 'Blue' },
          { emoji: '🟢', label: 'Green' },
        ],
        answer: '🔵',
        praise: 'That\'s right — it\'s BLUE! 💙',
        tip: 'Name the color clearly and have them repeat it. Find something blue in the room!',
      },
      {
        icon: '⭐⭐',
        text: 'How many stars do you see?',
        sub: 'Count the shiny stars!',
        choices: [
          { emoji: '1️⃣', label: 'One' },
          { emoji: '2️⃣', label: 'Two' },
          { emoji: '3️⃣', label: 'Three' },
          { emoji: '5️⃣', label: 'Five' },
        ],
        answer: '2️⃣',
        praise: 'Two stars! You\'re a star too! ⭐',
        tip: 'Hold up fingers together. Say: "One star… two stars!" Clap for each one.',
      },
      {
        icon: '🟡',
        text: 'What color is this circle?',
        sub: 'Can you name the color?',
        choices: [
          { emoji: '🟡', label: 'Yellow' },
          { emoji: '🔵', label: 'Blue' },
          { emoji: '🟢', label: 'Green' },
          { emoji: '🟣', label: 'Purple' },
        ],
        answer: '🟡',
        praise: 'Yellow — like sunshine! ☀️',
        tip: 'Point to something yellow nearby. The sun is yellow too!',
      },
      {
        icon: '🐶🐶🐶🐶',
        text: 'How many dogs are there?',
        sub: 'Count the puppies!',
        choices: [
          { emoji: '2️⃣', label: 'Two' },
          { emoji: '3️⃣', label: 'Three' },
          { emoji: '4️⃣', label: 'Four' },
          { emoji: '5️⃣', label: 'Five' },
        ],
        answer: '4️⃣',
        praise: 'Four dogs! Woof woof woof woof! 🐶',
        tip: 'Bark once for each dog together — makes counting fun and memorable!',
      },
      {
        icon: '🔴',
        text: 'What color is this?',
        sub: 'What is the name of this color?',
        choices: [
          { emoji: '🟠', label: 'Orange' },
          { emoji: '🔴', label: 'Red' },
          { emoji: '🟤', label: 'Brown' },
          { emoji: '🟣', label: 'Purple' },
        ],
        answer: '🔴',
        praise: 'Red! Like a fire truck! 🚒',
        tip: 'Ask: what else is red? Tomatoes, fire trucks, strawberries — have fun naming!',
      },
      {
        icon: '🌸🌸🌸🌸🌸',
        text: 'How many flowers?',
        sub: 'Count the pretty flowers!',
        choices: [
          { emoji: '3️⃣', label: 'Three' },
          { emoji: '4️⃣', label: 'Four' },
          { emoji: '5️⃣', label: 'Five' },
          { emoji: '6️⃣', label: 'Six' },
        ],
        answer: '5️⃣',
        praise: 'Five flowers! You\'re blooming! 🌸',
        tip: 'Count by tapping a finger for each flower. Nice slow pace — one, two, three, four, five!',
      },
      {
        icon: '🟢',
        text: 'What color is this circle?',
        sub: 'Name this color!',
        choices: [
          { emoji: '🔵', label: 'Blue' },
          { emoji: '🟡', label: 'Yellow' },
          { emoji: '🟢', label: 'Green' },
          { emoji: '🔴', label: 'Red' },
        ],
        answer: '🟢',
        praise: 'Green — like grass and frogs! 🐸',
        tip: 'Say: "Green like a frog!" Make a frog sound together — ribbit ribbit!',
      },
    ],
  },

  abc: {
    title: '🔤 ABCs',
    progressColor: '#00b894',
    cardClass: 'wc-abc',
    questions: [
      {
        icon: '🍎',
        text: 'Apple starts with which letter?',
        sub: 'Aa... Aa... Apple!',
        choices: [
          { emoji: 'A', label: 'A' },
          { emoji: 'B', label: 'B' },
          { emoji: 'C', label: 'C' },
          { emoji: 'D', label: 'D' },
        ],
        answer: 'A',
        praise: 'A is for Apple! Great job! 🍎',
        tip: 'Make a big A shape with your arms raised. Say "Aaa — Apple!" together.',
      },
      {
        icon: '🐻',
        text: 'Bear starts with which letter?',
        sub: 'Bb... Bb... Bear!',
        choices: [
          { emoji: 'A', label: 'A' },
          { emoji: 'B', label: 'B' },
          { emoji: 'C', label: 'C' },
          { emoji: 'D', label: 'D' },
        ],
        answer: 'B',
        praise: 'B is for Bear! Roar! 🐻',
        tip: 'Growl like a bear together, then say "B!" Name other B words: ball, banana, bird.',
      },
      {
        icon: '🐱',
        text: 'Cat starts with which letter?',
        sub: 'Cc... Cc... Cat!',
        choices: [
          { emoji: 'B', label: 'B' },
          { emoji: 'C', label: 'C' },
          { emoji: 'D', label: 'D' },
          { emoji: 'E', label: 'E' },
        ],
        answer: 'C',
        praise: 'C is for Cat! Meow! 🐱',
        tip: 'Meow together! Then list C words: cat, car, cup, cake.',
      },
      {
        icon: '🦆',
        text: 'Duck starts with which letter?',
        sub: 'Dd... Dd... Duck!',
        choices: [
          { emoji: 'C', label: 'C' },
          { emoji: 'D', label: 'D' },
          { emoji: 'E', label: 'E' },
          { emoji: 'F', label: 'F' },
        ],
        answer: 'D',
        praise: 'D is for Duck! Quack! 🦆',
        tip: 'Waddle like a duck and quack together! D, D, Duck!',
      },
      {
        icon: '🥚',
        text: 'Egg starts with which letter?',
        sub: 'Ee... Ee... Egg!',
        choices: [
          { emoji: 'D', label: 'D' },
          { emoji: 'E', label: 'E' },
          { emoji: 'F', label: 'F' },
          { emoji: 'G', label: 'G' },
        ],
        answer: 'E',
        praise: 'E is for Egg! You cracked it! 🥚',
        tip: 'Pretend to crack an egg open. Say "Eee — Egg!" together.',
      },
      {
        icon: '🐸',
        text: 'Frog starts with which letter?',
        sub: 'Ff... Ff... Frog!',
        choices: [
          { emoji: 'E', label: 'E' },
          { emoji: 'F', label: 'F' },
          { emoji: 'G', label: 'G' },
          { emoji: 'H', label: 'H' },
        ],
        answer: 'F',
        praise: 'F is for Frog! Ribbit! 🐸',
        tip: 'Jump like a frog! Ribbit, ribbit — F, F, Frog!',
      },
      {
        icon: '🍇',
        text: 'Grapes starts with which letter?',
        sub: 'Gg... Gg... Grapes!',
        choices: [
          { emoji: 'F', label: 'F' },
          { emoji: 'G', label: 'G' },
          { emoji: 'H', label: 'H' },
          { emoji: 'I', label: 'I' },
        ],
        answer: 'G',
        praise: 'G is for Grapes! Yummy! 🍇',
        tip: 'Ask: do you like grapes? G words: grapes, goat, game, girl!',
      },
      {
        icon: '🏠',
        text: 'House starts with which letter?',
        sub: 'Hh... Hh... House!',
        choices: [
          { emoji: 'G', label: 'G' },
          { emoji: 'H', label: 'H' },
          { emoji: 'I', label: 'I' },
          { emoji: 'J', label: 'J' },
        ],
        answer: 'H',
        praise: 'H is for House! Home sweet home! 🏠',
        tip: 'Make a roof shape above your head with your hands. H — House!',
      },
    ],
  },

  feelings: {
    title: '😊 Feelings',
    progressColor: '#9b59b6',
    cardClass: 'wc-feelings',
    questions: [
      {
        icon: '😄',
        text: 'This friend is feeling...',
        sub: 'How does this face look?',
        choices: [
          { emoji: '😄', label: 'Happy' },
          { emoji: '😢', label: 'Sad' },
          { emoji: '😠', label: 'Angry' },
          { emoji: '😨', label: 'Scared' },
        ],
        answer: '😄',
        praise: 'Happy! That big smile shows happiness! 😄',
        tip: 'Make a big happy smile together! Ask: "When do YOU feel happy?"',
      },
      {
        icon: '😢',
        text: 'This friend is feeling...',
        sub: 'Look at their eyes — any tears?',
        choices: [
          { emoji: '😄', label: 'Happy' },
          { emoji: '😢', label: 'Sad' },
          { emoji: '😮', label: 'Surprised' },
          { emoji: '😴', label: 'Sleepy' },
        ],
        answer: '😢',
        praise: 'Sad — it\'s okay to feel sad sometimes. 🤗',
        tip: 'Show a sad face and give a comforting hug. When do we feel sad? What helps?',
      },
      {
        icon: '😠',
        text: 'This friend is feeling...',
        sub: 'Notice the eyebrows!',
        choices: [
          { emoji: '😄', label: 'Happy' },
          { emoji: '😢', label: 'Sad' },
          { emoji: '😠', label: 'Angry' },
          { emoji: '🤔', label: 'Thinking' },
        ],
        answer: '😠',
        praise: 'Angry — and that\'s okay! We can calm down. 😌',
        tip: 'Talk about what makes us angry. What helps us feel better — a hug, deep breath?',
      },
      {
        icon: '😮',
        text: 'This friend is feeling...',
        sub: 'Look at that open mouth!',
        choices: [
          { emoji: '😮', label: 'Surprised' },
          { emoji: '😴', label: 'Sleepy' },
          { emoji: '😄', label: 'Happy' },
          { emoji: '😨', label: 'Scared' },
        ],
        answer: '😮',
        praise: 'Surprised! Oh wow! 😮',
        tip: 'Jump up surprised together! Ask: "Tell me a time you were surprised!"',
      },
      {
        icon: '😴',
        text: 'This friend is feeling...',
        sub: 'Do you see the sleepy eyes?',
        choices: [
          { emoji: '😢', label: 'Sad' },
          { emoji: '😴', label: 'Sleepy' },
          { emoji: '😠', label: 'Angry' },
          { emoji: '😄', label: 'Happy' },
        ],
        answer: '😴',
        praise: 'Sleepy — time for a nap! 😴',
        tip: 'Yawn together dramatically! Talk about bedtime routines and why sleep is important.',
      },
      {
        icon: '😨',
        text: 'This friend is feeling...',
        sub: 'Big eyes — what does that mean?',
        choices: [
          { emoji: '😨', label: 'Scared' },
          { emoji: '😄', label: 'Happy' },
          { emoji: '😢', label: 'Sad' },
          { emoji: '😮', label: 'Surprised' },
        ],
        answer: '😨',
        praise: 'Scared — everyone feels scared sometimes! 🫂',
        tip: 'Give a reassuring hug. Ask: "What makes YOU feel scared?" and "Who do you go to?"',
      },
      {
        icon: '🤔',
        text: 'This friend is feeling...',
        sub: 'Hand on chin — they\'re thinking!',
        choices: [
          { emoji: '😄', label: 'Happy' },
          { emoji: '🤔', label: 'Thinking' },
          { emoji: '😢', label: 'Sad' },
          { emoji: '😮', label: 'Surprised' },
        ],
        answer: '🤔',
        praise: 'Thinking! Just like YOU right now! 🧠',
        tip: 'Put your hand on your chin together. Ask: "What do you think about?"',
      },
      {
        icon: '🥰',
        text: 'This friend is feeling...',
        sub: 'Hearts in the eyes!',
        choices: [
          { emoji: '😠', label: 'Angry' },
          { emoji: '😢', label: 'Sad' },
          { emoji: '🥰', label: 'Loved' },
          { emoji: '😨', label: 'Scared' },
        ],
        answer: '🥰',
        praise: 'Loved! You are so loved! 💕',
        tip: 'Give a big hug! Ask: "Who makes YOU feel loved?" — family, friends, pets!',
      },
    ],
  },

  shapes: {
    title: '🔷 Shapes',
    progressColor: '#0984e3',
    cardClass: 'wc-shapes',
    questions: [
      {
        icon: '🔵',
        text: 'What shape is this?',
        sub: 'Round and round!',
        choices: [
          { emoji: '⬛', label: 'Square' },
          { emoji: '🔵', label: 'Circle' },
          { emoji: '🔺', label: 'Triangle' },
          { emoji: '▬', label: 'Rectangle' },
        ],
        answer: '🔵',
        praise: 'Circle! Round like the sun! ☀️',
        tip: 'Draw a circle in the air with your finger together. What else is a circle shape?',
      },
      {
        icon: '🔺',
        text: 'What shape is this?',
        sub: 'Count the corners — 1, 2, 3!',
        choices: [
          { emoji: '🔵', label: 'Circle' },
          { emoji: '⬛', label: 'Square' },
          { emoji: '🔺', label: 'Triangle' },
          { emoji: '⬜', label: 'Rectangle' },
        ],
        answer: '🔺',
        praise: 'Triangle! Three sides, three corners! 🔺',
        tip: 'Make a triangle shape above your head with both hands. Count the sides together!',
      },
      {
        icon: '⬛',
        text: 'What shape is this?',
        sub: 'Four equal sides!',
        choices: [
          { emoji: '🔺', label: 'Triangle' },
          { emoji: '⬛', label: 'Square' },
          { emoji: '🔵', label: 'Circle' },
          { emoji: '⭐', label: 'Star' },
        ],
        answer: '⬛',
        praise: 'Square! Four equal sides! ⬛',
        tip: 'Trace a square with your finger on a table. Find a square in the room!',
      },
      {
        icon: '⭐',
        text: 'What shape is this?',
        sub: 'It shines in the sky at night!',
        choices: [
          { emoji: '🔵', label: 'Circle' },
          { emoji: '🔺', label: 'Triangle' },
          { emoji: '⭐', label: 'Star' },
          { emoji: '🔷', label: 'Diamond' },
        ],
        answer: '⭐',
        praise: 'Star! You\'re a star too! ⭐',
        tip: 'Spread your fingers wide like a star! Twinkle twinkle little star!',
      },
      {
        icon: '🔷',
        text: 'What shape is this?',
        sub: 'Like a tilted square!',
        choices: [
          { emoji: '⬛', label: 'Square' },
          { emoji: '🔵', label: 'Circle' },
          { emoji: '🔷', label: 'Diamond' },
          { emoji: '🔺', label: 'Triangle' },
        ],
        answer: '🔷',
        praise: 'Diamond! Shiny and beautiful! 💎',
        tip: 'Find a diamond shape together — like a kite or a baseball field!',
      },
      {
        icon: '🟥',
        text: 'What shape is this?',
        sub: 'Longer on two sides!',
        choices: [
          { emoji: '⬛', label: 'Square' },
          { emoji: '🟥', label: 'Rectangle' },
          { emoji: '🔵', label: 'Circle' },
          { emoji: '⭐', label: 'Star' },
        ],
        answer: '🟥',
        praise: 'Rectangle! Like a door or a book! 📚',
        tip: 'Find rectangles in the room — books, doors, windows! Count the sides.',
      },
      {
        icon: '🔵🔺⬛',
        text: 'Which shape has NO corners?',
        sub: 'Corners are the pointy bits!',
        choices: [
          { emoji: '🔺', label: 'Triangle' },
          { emoji: '⬛', label: 'Square' },
          { emoji: '🔵', label: 'Circle' },
          { emoji: '⭐', label: 'Star' },
        ],
        answer: '🔵',
        praise: 'Circle! Smooth all the way round! 🔵',
        tip: 'Run your finger around a circle shape — no bumps, no corners! So smooth!',
      },
      {
        icon: '🔺',
        text: 'How many sides does a triangle have?',
        sub: 'Count the sides!',
        choices: [
          { emoji: '2️⃣', label: 'Two' },
          { emoji: '3️⃣', label: 'Three' },
          { emoji: '4️⃣', label: 'Four' },
          { emoji: '5️⃣', label: 'Five' },
        ],
        answer: '3️⃣',
        praise: 'Three! Tri means three! 🔺',
        tip: 'Count along each side with your finger. One, two, three — triangle!',
      },
    ],
  },

  social: {
    title: '🤝 Friends & Sharing',
    progressColor: '#e84393',
    cardClass: 'wc-social',
    questions: [
      {
        icon: '🤝',
        text: 'When you meet someone new, you...',
        sub: 'What\'s the friendly thing to do?',
        choices: [
          { emoji: '👋', label: 'Say hello!' },
          { emoji: '😤', label: 'Walk away' },
          { emoji: '😴', label: 'Sleep' },
          { emoji: '🙈', label: 'Hide' },
        ],
        answer: '👋',
        praise: 'Say hello! You\'re so friendly! 👋',
        tip: 'Practice greeting together: "Hi, my name is ___! Nice to meet you!" with a wave!',
      },
      {
        icon: '🍪🍪',
        text: 'You have 2 cookies. Your friend has none. You...',
        sub: 'Being a good friend means...',
        choices: [
          { emoji: '😊', label: 'Share one!' },
          { emoji: '🙅', label: 'Keep both' },
          { emoji: '😤', label: 'Run away' },
          { emoji: '😴', label: 'Ignore them' },
        ],
        answer: '😊',
        praise: 'Share! Sharing makes BOTH friends happy! 🍪',
        tip: 'Practice sharing with a toy or snack. "Would you like some?" — model the words!',
      },
      {
        icon: '😢',
        text: 'Your friend is sad. You...',
        sub: 'How can you help?',
        choices: [
          { emoji: '🤗', label: 'Give a hug' },
          { emoji: '😂', label: 'Laugh at them' },
          { emoji: '🏃', label: 'Run away' },
          { emoji: '📺', label: 'Watch TV' },
        ],
        answer: '🤗',
        praise: 'Give a hug! You\'re such a kind friend! 🤗',
        tip: 'Practice giving a gentle hug. Talk about how a hug can help someone feel better.',
      },
      {
        icon: '🧸',
        text: 'Your friend wants to play with your toy. You...',
        sub: 'What would a kind friend do?',
        choices: [
          { emoji: '🤲', label: 'Let them try' },
          { emoji: '🙅', label: 'Say no always' },
          { emoji: '😠', label: 'Get angry' },
          { emoji: '🏃', label: 'Hide the toy' },
        ],
        answer: '🤲',
        praise: 'Share and take turns — that\'s kind! 🧸',
        tip: 'Practice: "You can have a turn, then I\'ll have my turn." Take turns with a toy!',
      },
      {
        icon: '🗣️',
        text: 'Someone is speaking. You...',
        sub: 'What\'s the respectful thing to do?',
        choices: [
          { emoji: '👂', label: 'Listen quietly' },
          { emoji: '📣', label: 'Talk over them' },
          { emoji: '😴', label: 'Fall asleep' },
          { emoji: '🏃', label: 'Walk away' },
        ],
        answer: '👂',
        praise: 'Listen! Good listeners are great friends! 👂',
        tip: 'Practice quiet listening together. Make eye contact, nod — show you\'re listening!',
      },
      {
        icon: '🎮',
        text: 'It\'s your friend\'s turn to play. You...',
        sub: 'We all get a turn!',
        choices: [
          { emoji: '⏳', label: 'Wait patiently' },
          { emoji: '😭', label: 'Cry and grab' },
          { emoji: '😠', label: 'Push them' },
          { emoji: '🏃', label: 'Run away' },
        ],
        answer: '⏳',
        praise: 'Wait patiently — your turn is coming! ⏳',
        tip: 'Practice waiting together. Count to 10 slowly. "Your turn is almost here!"',
      },
      {
        icon: '🤕',
        text: 'You accidentally bump your friend. You say...',
        sub: 'Oops! What\'s the right thing to say?',
        choices: [
          { emoji: '😞', label: 'Sorry!' },
          { emoji: '😤', label: 'Not sorry' },
          { emoji: '🏃', label: 'Run away' },
          { emoji: '😂', label: 'Laugh at them' },
        ],
        answer: '😞',
        praise: 'Sorry! Saying sorry is so brave! 💪',
        tip: 'Practice saying sorry with a kind voice and face. "I\'m sorry, are you okay?"',
      },
      {
        icon: '🎉',
        text: 'Your friend wins a game. You say...',
        sub: 'Being a good sport means...',
        choices: [
          { emoji: '👏', label: 'Well done!' },
          { emoji: '😠', label: 'Get angry' },
          { emoji: '😭', label: 'Cry and sulk' },
          { emoji: '🙅', label: 'Refuse to play' },
        ],
        answer: '👏',
        praise: 'Cheer for your friend! That\'s sportsmanship! 👏',
        tip: 'Practice clapping and saying "Well done!" together. It feels good to celebrate others!',
      },
    ],
  },

  animals: {
    title: '🐾 Animals',
    progressColor: '#27ae60',
    cardClass: 'wc-animals',
    questions: [
      {
        icon: '🐶',
        text: 'What sound does a dog make?',
        sub: 'Can you make the sound?',
        choices: [
          { emoji: '🐱', label: 'Meow' },
          { emoji: '🐶', label: 'Woof!' },
          { emoji: '🐮', label: 'Moo' },
          { emoji: '🐸', label: 'Ribbit' },
        ],
        answer: '🐶',
        praise: 'Woof woof! You sound just like a dog! 🐶',
        tip: 'Bark together! Ask: "Have you ever met a dog? What was it like?"',
      },
      {
        icon: '🐱',
        text: 'What sound does a cat make?',
        sub: 'Listen and choose!',
        choices: [
          { emoji: '🐶', label: 'Woof' },
          { emoji: '🐱', label: 'Meow!' },
          { emoji: '🐮', label: 'Moo' },
          { emoji: '🦆', label: 'Quack' },
        ],
        answer: '🐱',
        praise: 'Meow! Cats say meow! 🐱',
        tip: 'Meow together! Purr too. Ask if they have a cat or have seen one.',
      },
      {
        icon: '🐮',
        text: 'What sound does a cow make?',
        sub: 'Think of a farm!',
        choices: [
          { emoji: '🐶', label: 'Woof' },
          { emoji: '🐱', label: 'Meow' },
          { emoji: '🐮', label: 'Moo!' },
          { emoji: '🐑', label: 'Baa' },
        ],
        answer: '🐮',
        praise: 'Moooo! A cow says moo! 🐮',
        tip: 'Moooo together as loud as you can! Cows live on farms and give us milk.',
      },
      {
        icon: '🐸',
        text: 'Where does a frog live?',
        sub: 'Think of somewhere wet!',
        choices: [
          { emoji: '🏔️', label: 'Mountain' },
          { emoji: '🌊', label: 'Pond / Water' },
          { emoji: '🏜️', label: 'Desert' },
          { emoji: '❄️', label: 'Snow' },
        ],
        answer: '🌊',
        praise: 'Near water — ponds and lakes! 🐸',
        tip: 'Jump like a frog! Ribbit ribbit! Frogs love to swim and jump near ponds.',
      },
      {
        icon: '🦋',
        text: 'A butterfly starts life as a...',
        sub: 'It changes as it grows!',
        choices: [
          { emoji: '🐣', label: 'Baby bird' },
          { emoji: '🐛', label: 'Caterpillar' },
          { emoji: '🐟', label: 'Fish' },
          { emoji: '🐝', label: 'Bee' },
        ],
        answer: '🐛',
        praise: 'Caterpillar! Then it grows wings! 🦋',
        tip: 'Crawl like a caterpillar together, then spread your arms like wings — transform!',
      },
      {
        icon: '🐘',
        text: 'What is special about an elephant?',
        sub: 'Think about its face!',
        choices: [
          { emoji: '🦕', label: 'Long neck' },
          { emoji: '🦛', label: 'Horn' },
          { emoji: '🐘', label: 'Big trunk' },
          { emoji: '🦒', label: 'Spots' },
        ],
        answer: '🐘',
        praise: 'A big trunk! Elephants use it to drink! 🐘',
        tip: 'Dangle your arm like a trunk and make elephant sounds! Elephants are the biggest land animals.',
      },
      {
        icon: '🐦',
        text: 'How do birds get around?',
        sub: 'Think about what they use!',
        choices: [
          { emoji: '🏊', label: 'Swimming' },
          { emoji: '🦅', label: 'Flying' },
          { emoji: '🏃', label: 'Running only' },
          { emoji: '🚗', label: 'Driving' },
        ],
        answer: '🦅',
        praise: 'Flying! Wings take them up in the sky! 🐦',
        tip: 'Flap your arms like wings together! Soar around the room like a bird!',
      },
      {
        icon: '🐠',
        text: 'Where does a fish live?',
        sub: 'Home sweet home for a fish!',
        choices: [
          { emoji: '🌲', label: 'In a tree' },
          { emoji: '🌊', label: 'In water' },
          { emoji: '🏠', label: 'In a house' },
          { emoji: '☁️', label: 'In the sky' },
        ],
        answer: '🌊',
        praise: 'In water — rivers, lakes, and oceans! 🐠',
        tip: 'Pretend to swim together! Make a fish face. Fish breathe through their gills underwater.',
      },
    ],
  },
};
